<a href="https://colab.research.google.com/github/Rajaanthonysamy/movie_recommendation_nlp/blob/main/RecommendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("CooperUnion/anime-recommendations-database")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/anime-recommendations-database


In [6]:
df=pd.read_csv("/kaggle/input/anime-recommendations-database/anime.csv")
rating_df=pd.read_csv("/kaggle/input/anime-recommendations-database/rating.csv")

In [7]:
df.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [8]:
df.describe()

anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [9]:
rating_df.head(2)

user_id  anime_id  rating
0        1        20      -1
1        1        24      -1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12232 non-null  object 
 3   type      12269 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB


In [11]:
df=df.dropna()

In [12]:
df.isna().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [13]:
df["description"]=df["name"]+" "+df["genre"]+" "+df['type']+" episodes : " +df["episodes"]+" rating : "+df["rating"].astype(str)

In [14]:
df.head(2)

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   

   members                                        description  
0   200630  Kimi no Na wa. Drama, Romance, School, Superna...  
1   793665  Fullmetal Alchemist: Brotherhood Action, Adven...

In [15]:
from transformers import AutoTokenizer, TFAutoModel
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [16]:
tokenizer=  AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
model= TFAutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['embeddings.position_ids']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [17]:
sentences=["horror movie","funny movie"]
encoded_point= tokenizer(sentences,padding=True,truncation=True,return_tensors="tf")

In [18]:
encoded_point

{'input_ids': <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 101, 5469, 3185,  102],
       [ 101, 6057, 3185,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>}

In [19]:
encoded_point['input_ids']

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 101, 5469, 3185,  102],
       [ 101, 6057, 3185,  102]], dtype=int32)>

In [20]:
encoded_point['attention_mask']

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [21]:
model_output=model(input_ids=encoded_point['input_ids'], attention_mask=encoded_point['attention_mask'])

In [22]:
model_output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 4, 384), dtype=float32, numpy=
array([[[-0.15981497, -0.21450824, -0.08092972, ..., -0.04026801,
         -0.20147711, -0.19799148],
        [-0.20690474,  0.2555588 , -0.6293315 , ..., -0.7395627 ,
         -0.21265659, -0.10199238],
        [-0.62115574,  0.46876404, -1.1121507 , ..., -0.38965517,
          0.6914278 ,  0.40979314],
        [-1.0488122 ,  0.573788  , -0.95528436, ..., -0.12775624,
          0.20759782,  0.33106968]],

       [[-0.26984325, -0.284725  , -0.18559906, ..., -0.2104583 ,
         -0.16816834, -0.04650535],
        [-0.5479527 , -0.01438649, -0.40429536, ...,  0.45052537,
          0.37021965,  0.02968785],
        [-0.8886989 ,  0.51917255, -0.85248613, ..., -0.29348746,
          0.89073396,  0.02339553],
        [-0.46686783,  0.12276877, -0.63008726, ..., -0.45931494,
          0.27658814,  0.09754112]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(2, 384), dty

In [26]:
def mean_pooling(model_output, attention_mask):
  token_embeddings=model_output[0]
  input_mask_expanded = tf.cast(tf.expand_dims(attention_mask, -1), tf.float32)
  masked_embeddings = token_embeddings * input_mask_expanded
  return tf.math.reduce_sum(masked_embeddings, axis=1) / tf.math.maximum(tf.math.reduce_sum(input_mask_expanded, axis=1), 1e-9)

In [28]:
sentence_embedding=mean_pooling(model_output,encoded_point['attention_mask'])